In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/alqiya/olympics/olympics-data.xlsx

In [2]:
import pandas as pd

#making a dataframe manually

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])
df
print(df.index)
print(df.columns)
print(df.info())
print(df.describe())

RangeIndex(start=0, stop=3, step=1)
Index(['A', 'B', 'C'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None
         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [3]:
# finding unique values in each column
print(df.nunique())

# to find unique values in a single column
print(df['A'].nunique())

#to find shape(rowxcol)
print(df.shape)

# to find the number of items in df
print(df.size)

A    3
B    3
C    3
dtype: int64
3
(3, 3)
9

In [4]:
# getting started with easy data 
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
coffee.head(5)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

****Loading different datasets****

In [5]:
olympics = pd.read_excel("/kaggle/input/datasets/alqiya/olympics/olympics-data.xlsx")
olympics.head(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [6]:
bios = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")
results = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv")

### ****Accsessing data with pandas****

In [7]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
#loc and iloc
# df.loc[rows, cols]

print(coffee.loc[[1,2,3]])
print(coffee.loc[[1,2,5,8]])
print(coffee.loc[0:3 , "Day"]) # 3 is inclusive
print(coffee.loc[0:, ["Day","Units Sold"]])
print(coffee.loc[3:])

       Day Coffee Type  Units Sold
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20
         Day Coffee Type  Units Sold
1     Monday       Latte          15
2    Tuesday    Espresso          30
5  Wednesday       Latte          25
8     Friday    Espresso          45
0     Monday
1     Monday
2    Tuesday
3    Tuesday
Name: Day, dtype: object
          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35
          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [9]:
#iloc[rows, cols]

coffee.iloc[0:3, 0:2]

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso

In [10]:
# Accessing particular column

# print(coffee.Day)
# print(coffee[["Day","Coffee Type"]])

In [11]:
# sorting
coffee.sort_values("Units Sold", ascending = False)

# sorting by 2 cols
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [12]:
for index, rows in coffee.iterrows():
    print(index)
    print(rows)
    print('\n')

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object


1
Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object


2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object


3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object


4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object


5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object


6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object


7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object


8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object


9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object


10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object


11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object


12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object


13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

### Filtering Data

In [13]:
bios.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [14]:
bios.loc[bios["height_cm"]>215, ["name", "height_cm"]]
# OR
bios[bios["height_cm"]>220][["name", "height_cm"]]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

In [15]:
#multiple conditions

bios[(bios["height_cm"]>210) & (bios["born_country"]=="USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5681,5704,Walt Bellamy,1937-07-24,New Bern,North Carolina,USA,United States,211.0,98.0,2013-11-02
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5894,5919,Mel Counts,1941-10-16,Coos Bay,Oregon,USA,United States,213.0,102.0,NaN
6106,6133,Marc Freiberger,1928-11-27,Amarillo,Texas,USA,United States,211.0,98.0,2005-06-29
6281,6309,Darrall Imhoff,1938-10-11,San Gabriel,California,USA,United States,211.0,98.0,2017-06-30
6379,6410,Joe Kleine,1962-01-04,Colorado Springs,Colorado,USA,United States,211.0,122.0,NaN
6393,6424,Jon Koncak,1963-05-17,Cedar Rapids,Iowa,USA,United States,213.0,113.0,NaN
6442,6473,Christian Laettner,1969-08-17,Angola,New York,USA,United States,211.0,107.0,NaN
6615,6648,Tom McMillen,1952-05-26,Mansfield,Pennsylvania,USA,United States,212.0,95.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
7012,7048,Daniel Santiago,1976-06-24,Tarpon Springs,Florida,USA,Puerto Rico,213.0,111.0,NaN
112319,113575,Chris Kaman,1982-04-28,Wyoming,Michigan,USA,Germany,213.0,122.0,NaN
112366,113622,Dwight Howard,1985-12-08,Atlanta,Georgia,USA,United States,211.0,120.0,NaN
118573,120309,Al-Farouq Aminu,1990-09-21,Atlanta,Georgia,USA,Nigeria,211.0,98.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
132188,135037,Domantas Sabonis,1996-05-03,Portland,Oregon,USA,Lithuania,211.0,109.0,NaN
133332,136271,DeAndre Jordan,1988-07-21,Houston,Texas,USA,United States,211.0,120.0,NaN
142044,145640,Jahlil Okafor,1995-12-15,Fort Smith,Arkansas,USA,Nigeria,211.0,NaN,NaN
142930,146560,Mike Tobey,1994-10-10,Monroe,New York,USA,Slovenia,213.0,NaN,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN

In [16]:
bios[bios['name'].str.contains("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [17]:
bios.query('born_country == "USA"' and 'born_city=="Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

### ADD/Remove Columns

In [18]:
coffee["price"]=4.99
coffee["new_price"]=np.where(coffee["Coffee Type"]=="Espresso", 3.99, 5.99) 
# coffee type= espresso then val=3.99 else =5.99
coffee

coffee.drop(columns=["price"], inplace=True)
# coffee.drop([0,1,2])

coffee_new = coffee
Now any changes, if, we make to coffee_new will be reflected in coffee cause both of them are pointing to the same memory location.
To prevent this from happenning we use copy()

coffee_new = coffeee.copy()
Now the changes won't be reflected in the coffee df

If we make changes to coffee then a new dataframe is initialized or created
To prevent this from happening, we use inplace=True

In [19]:
coffee["revenue"] = coffee["Units Sold"] * coffee["new_price"]
coffee.head(5)

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

In [20]:
# rename
coffee.rename(columns={'new_price':'price'}, inplace=True)
coffee.head(3)

       Day Coffee Type  Units Sold  price  revenue
0   Monday    Espresso          25   3.99    99.75
1   Monday       Latte          15   5.99    89.85
2  Tuesday    Espresso          30   3.99   119.70

In [21]:
bios_new = bios.copy()
bios_new["first_name"] = bios_new['name'].str.split(" ").str[0]
# bios_new.query('first_name =="Keith"')
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud

In [22]:
bios_new['born_date'] = pd.to_datetime(bios_new['born_date'])
bios_new['born_year'] = bios_new["born_date"].dt.year
print(bios_new.head(3))
print("\n\n")
print(bios.info())

   athlete_id                   name  born_date born_city  \
0           1  Jean-François Blanchy 1886-12-12  Bordeaux
1           2         Arnaud Boetsch 1969-04-01    Meulan
2           3           Jean Borotra 1898-08-13  Biarritz

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN
1              Yvelines          FRA  France      183.0       76.0
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0

    died_date     first_name  born_year
0  1960-10-02  Jean-François     1886.0
1         NaN         Arnaud     1969.0
2  1994-07-17           Jean     1898.0



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB
None

In [23]:
#adding new col
bios_new['height'] = bios_new["height_cm"].apply(lambda x: "Short" if x<165 else ("Average" if x <185 else "Tall" ))
bios_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,height
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,Average

In [24]:
def categorize_athlete(row):
    if row["height_cm"]<170 and row['weight_kg']<70:
        return "lightweight"
    elif row["height_cm"]<180 or row['weight_kg']<=80:
        return "heavyweight"
    else:
        return "normal"
bios_new['category'] = bios_new.apply(categorize_athlete, axis=1) # axis = 1-->rows, axis = 0-->cols
bios_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,height,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall,normal
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,Average,heavyweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,Average,heavyweight

In [25]:
nocs =  pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/noc_regions.csv")
nocs.head(3)

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN

In [26]:
results.head(3)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN

In [27]:
combined_df = pd.merge(results, bios, on = "athlete_id", how="left")

In [28]:
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN

### **Handling Null Value**

1. fillna()

   a)df.fillna(value) #replaces null values in the col with value
   b) df.fillna(df.col.mean()) #fills the null value with the mean of the col

2. interpolate()

    df.colname.inetrpolate() #fills the missing value by observing the pattern from the neighbors

3. dropna()

    a) df.dropna(axis=0, how='any', subset=['col_name'], thresh=None, inplace=True)
        #removes the rows if axis=0 and cols if aixs =1,
        #how=any-->if any valu in row or col is nul remove it,,how=all-->removes only if all the values in row or col are nan

### **Aggregating Data**

In [44]:
bios["born_city"].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [45]:
#finding the athletes from usa in each region
bios[bios["born_country"]=="USA"]["born_region"].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [49]:
# group by function
cof = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
cof.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [50]:
cof.groupby(["Coffee Type"])["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [53]:
cof.groupby(["Coffee Type"])["Units Sold"].mean()

#using.agg method
cof.groupby(['Coffee Type']).agg({"Units Sold":["sum","mean"]})

            Units Sold
                   sum       mean
Coffee Type
Espresso           265  37.857143
Latte              195  27.857143

In [56]:
cof["price"] = np.where(cof["Coffee Type"]=="Espresso", 5.99, 3.99)
cof["revenue"] = cof["price"] * cof["Units Sold"]
cof.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   3.99    59.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   3.99    79.80
4  Wednesday    Espresso          35   5.99   209.65

In [58]:
#pivot 
pivot_cof = cof.pivot(columns = "Coffee Type", index = "Day", values = 'revenue')
pivot_cof

Coffee Type  Espresso   Latte
Day
Friday         269.55  139.65
Monday         149.75   59.85
Saturday       269.55  139.65
Sunday         269.55  139.65
Thursday       239.60  119.70
Tuesday        179.70   79.80
Wednesday      209.65   99.75

In [59]:
pivot_cof.loc['Monday','Espresso']

np.float64(149.75)

In [62]:
pivot_cof.sum(axis = 1)

Day
Friday       409.2
Monday       209.6
Saturday     409.2
Sunday       409.2
Thursday     359.3
Tuesday      259.5
Wednesday    309.4
dtype: float64

In [63]:
bios.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN

In [72]:
bios["born_date"] =pd.to_datetime(bios['born_date'])
bios["month_born"] = bios["born_date"].dt.month
bios["year_born"] = bios["born_date"].dt.year
bios.groupby([bios["month_born"], bios["year_born"]])["name"].count().reset_index().sort_values('name',ascending=False)

      month_born  year_born  name
124          1.0     1970.0   239
126          1.0     1972.0   229
129          1.0     1975.0   227
140          1.0     1986.0   227
139          1.0     1985.0   225
...          ...        ...   ...
165          2.0     1853.0     1
168          2.0     1859.0     1
172          2.0     1864.0     1
7            1.0     1852.0     1
1884        12.0     2006.0     1

[1885 rows x 3 columns]

### **Advanced function**

.shift()
.rank()
.rolling()
.cumsum() #specific type of rolling func

In [73]:
#shift-->find the details of day before or something..used for comparision in time series data
#shift backwards by shift(-1)
cof["yesterday_revenue"] = cof["revenue"].shift(1)
cof.head()

         Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0     Monday    Espresso          25   5.99   149.75                NaN
1     Monday       Latte          15   3.99    59.85             149.75
2    Tuesday    Espresso          30   5.99   179.70              59.85
3    Tuesday       Latte          20   3.99    79.80             179.70
4  Wednesday    Espresso          35   5.99   209.65              79.80

In [77]:
#finding percentage change in revenue

cof["pct_change"] = cof["revenue"] / cof["yesterday_revenue"] *100
cof.head()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,5.99,149.75,NaN,NaN
1,Monday,Latte,15,3.99,59.85,149.75,39.966611
2,Tuesday,Espresso,30,5.99,179.70,59.85,300.250627
3,Tuesday,Latte,20,3.99,79.80,179.70,44.407346
4,Wednesday,Espresso,35,5.99,209.65,79.80,262.719298

In [78]:
#.rank()
bios["height_rank"] = bios['height_cm'].rank() 
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,12.0,1886.0,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,4.0,1969.0,79054.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,8.0,1898.0,79054.5
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,5.0,1895.0,22677.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,4.0,1878.0,NaN

In [81]:
bios.sort_values(["height_rank"], ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,9.0,1980.0,106651.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,12.0,1964.0,106649.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.0,1952.0,106649.5
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,11.0,1975.0,106647.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,11.0,1987.0,106647.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,6.0,1995.0,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,12.0,1989.0,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,4.0,1927.0,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,8.0,1998.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,7.0,1913.0,NaN

In [82]:
#can use github copilot
#rolling()
#cumsum-->cumulative revenue

cof.head()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,5.99,149.75,NaN,NaN
1,Monday,Latte,15,3.99,59.85,149.75,39.966611
2,Tuesday,Espresso,30,5.99,179.70,59.85,300.250627
3,Tuesday,Latte,20,3.99,79.80,179.70,44.407346
4,Wednesday,Espresso,35,5.99,209.65,79.80,262.719298

In [83]:
cof["cumulative_revenue"] = cof[r"revenue"].cumsum()

In [84]:
cof.head()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,25,5.99,149.75,NaN,NaN,149.75
1,Monday,Latte,15,3.99,59.85,149.75,39.966611,209.60
2,Tuesday,Espresso,30,5.99,179.70,59.85,300.250627,389.30
3,Tuesday,Latte,20,3.99,79.80,179.70,44.407346,469.10
4,Wednesday,Espresso,35,5.99,209.65,79.80,262.719298,678.75

In [85]:
# 3 day sales for latte
latte = cof[cof["Coffee Type"] == "Latte"].copy()
latte.head()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
1,Monday,Latte,15,3.99,59.85,149.75,39.966611,209.6
3,Tuesday,Latte,20,3.99,79.80,179.70,44.407346,469.1
5,Wednesday,Latte,25,3.99,99.75,209.65,47.579299,778.5
7,Thursday,Latte,30,3.99,119.70,239.60,49.958264,1137.8
9,Friday,Latte,35,3.99,139.65,269.55,51.808570,1547.0

In [87]:
latte["3_day_sales"] = latte['Units Sold'].rolling(3).sum()
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3_day_sales
1,Monday,Latte,15,3.99,59.85,149.75,39.966611,209.6,NaN
3,Tuesday,Latte,20,3.99,79.80,179.70,44.407346,469.1,NaN
5,Wednesday,Latte,25,3.99,99.75,209.65,47.579299,778.5,60.0
7,Thursday,Latte,30,3.99,119.70,239.60,49.958264,1137.8,75.0
9,Friday,Latte,35,3.99,139.65,269.55,51.808570,1547.0,90.0
11,Saturday,Latte,35,3.99,139.65,269.55,51.808570,1956.2,100.0
13,Sunday,Latte,35,3.99,139.65,269.55,51.808570,2365.4,105.0

### **New Functionality**

In [88]:
results_numpy = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv")
results_pandas = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv", engine='pyarrow', dtype_backend = 'pyarrow')

#pyarrow gives more optimization

In [89]:
pd.__version__

'2.3.3'

In [90]:
results_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB